### ISSUE TITLE
Set Logging Options Maxsize

### ISSUE THREAD

**Issue by kidneyweakx** [cathayddt/bdk#87]
### What is the problem that you are trying to solve?

docker container taking all disk space when running a times.

### 新功能 Feature Request

container log need config `log-opt` https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver

### 可能的解法 Proposed Solution

in all docker-compoese set the options max-size
```
version: '3'
services:
    app:
        ...
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
```
